branch-defaults:
  master:
    environment: process.env['AWS_ENV']
global:
  application_name: process.env['AWS_APP']
  default_platform: process.env['AWS_PLATFORM']
  default_region: process.env['AWS_DEFAULT_REGION']
  sc: git