version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  cypress: cypress-io/cypress@1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:4.2.0
       
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-dependencies
          command: npm install
      - run: 
          name: start-server
          command: npm start
      - run: 
          name: run-cypress
          command: npm run cy:run

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - hold
