# version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10
#   cypress: cypress-io/cypress@1

# workflows:
#   heroku_deploy:
#     jobs:
#       - cypress/run:
#           requires:
#             start: "npm start"
#       - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
version: 2.1

dependencies:
  cache_directories:
    - mongodb-linux-x86_64-ubuntu1204-3.2.0
  pre:
    - if [[ ! -d mongodb-linux-x86_64-ubuntu1204-3.2.0 ]]; then wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1204-3.2.0.tgz && tar xvzf mongodb-linux-x86_64-ubuntu1204-3.2.0.tgz; fi
    - sudo stop mongodb
    - sudo cp mongodb-linux-x86_64-ubuntu1204-3.2.0/bin/* /usr/bin
    - sudo start mongodb
machine:
  services:
    - mongodb

orbs:
  heroku: circleci/heroku@0.0.10
  cypress: cypress-io/cypress@1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:3.4.4
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: install-dependencies
            command: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          start: npm start
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - cypress/run
      - heroku/deploy-via-git:
          requires:
            - hold
