version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  eb: circleci/aws-elastic-beanstalk@1.0.2
  
# custom executor for the  Cypress orb
executors:
  mongo-executor:
    docker:
      - image: cypress/base:14
      - image: 
          mongo:4.4.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-dependencies
          command: npm install
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          command: |
            echo "region env variable set to: " + $AWS_DEFAULT_REGION
            eb deploy $AWS_ENV
            eb status
          name: You may now use the EB CLI within this job
    
  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          executor: mongo-executor
          start: npm start
          requires:
            - build
      - deploy:
          requires:
            - build
            - cypress/run