version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  cypress: cypress-io/cypress@1
  
# custom executor for the  Cypress orb
executors:
  mongo-executor:
    docker:
      - image: cypress/base:14
      - image: 
          mongo:4.4.0
      # - image: hasura/graphql-engine:v1.1.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/mongo:4.4.0
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-dependencies
          command: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          executor: mongo-executor
          start: npm start
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - cypress/run
      - heroku/deploy-via-git:
          requires:
            - hold
