# version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10
#   cypress: cypress-io/cypress@1

# workflows:
#   heroku_deploy:
#     jobs:
#       - cypress/run:
#           requires:
#             start: "npm start"
#       - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  cypress: cypress-io/cypress@1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - cypress/run
      - heroku/deploy-via-git:
          requires:
            - hold
