version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  
# custom executor for the  Cypress orb
executors:
  mongo-executor:
    docker:
      - image: cypress/base:14
      - image: 
          mongo:4.4.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-dependencies
          command: npm install
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy $AWS_ENV
    
  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          executor: mongo-executor
          start: npm start
          requires:
            - build
      - deploy:
          requires:
            - build
            - cypress/run
