version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  eb: circleci/aws-elastic-beanstalk@1.0.2
  
# custom executor for the  Cypress orb
executors:
  mongo-executor:
    docker:
      - image: cypress/base:14
      - image: 
          mongo:4.4.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-dependencies
          command: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          executor: mongo-executor
          start: npm start
          requires:
            - build
      - eb/deploy:
          context: aws-creds
          environment-name: $AWS_ENV
          filters:
            branches:
              only:
                - EB-Setup
          requires:
            - build
            - cypress/run
      